const { v4: uuidv4 } = require('uuid')

module.exports = (courseId) => [
  // Course 1
  {
    id: uuidv4(),
    no: 1,
    name: 'Pengenalan Dasar Web',
    courseId: courseId[0].id,
    totalDuration: 95,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 2,
    name: 'Pengenalan React JS',
    courseId: courseId[0].id,
    totalDuration: 70,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 3,
    name: 'Membangun Aplikasi Pertama',
    courseId: courseId[0].id,
    totalDuration: 110,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 4,
    name: 'Pengenalan Konsep Lanjutan',
    courseId: courseId[0].id,
    totalDuration: 95,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 5,
    name: 'Membuat Aplikasi Lebih Dinamis',
    courseId: courseId[0].id,
    totalDuration: 120,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 6,
    name: 'Projek Akhir',
    courseId: courseId[0].id,
    totalDuration: 45,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Course 2
  {
    id: uuidv4(),
    no: 1,
    name: 'Pengenalan UI/UX Design',
    courseId: courseId[1].id,
    totalDuration: 80,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 2,
    name: 'Memulai UI/UX design',
    courseId: courseId[1].id,
    totalDuration: 95,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 3,
    name: 'Proyek Desain UI/UX',
    courseId: courseId[1].id,
    totalDuration: 85,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 4,
    name: 'Karir dalam UI/UX Design',
    courseId: courseId[1].id,
    totalDuration: 50,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 1,
    name: 'Pendahuluan',
    courseId: courseId[2].id,
    totalDuration: 120,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 2,
    name: 'Memulai bahasa assembly x86',
    courseId: courseId[2].id,
    totalDuration: 60,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 3,
    name: 'Membuat aplikasi android menggunakan asembly x86',
    courseId: courseId[2].id,
    totalDuration: 120,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 1,
    name: 'Pendahuluan',
    courseId: courseId[3].id,
    totalDuration: 120,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 2,
    name: 'Membuat Restful API dengan C',
    courseId: courseId[3].id,
    totalDuration: 80,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 1,
    name: 'Pendahuluan',
    courseId: courseId[4].id,
    totalDuration: 40,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 2,
    name: 'Memulai Backend dengan Golang',
    courseId: courseId[4].id,
    totalDuration: 120,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 1,
    name: 'Pendahuluan',
    courseId: courseId[5].id,
    totalDuration: 50,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 2,
    name: 'Memulai Android Studio',
    courseId: courseId[5].id,
    totalDuration: 70,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 1,
    name: 'Pendahuluan',
    courseId: courseId[6].id,
    totalDuration: 90,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 2,
    name: 'Memulai UI/UX design',
    totalDuration: 80,
    courseId: courseId[6].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 1,
    name: 'Pendahuluan',
    courseId: courseId[7].id,
    totalDuration: 65,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 2,
    name: 'Memulai UI/UX design',
    courseId: courseId[7].id,
    totalDuration: 105,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 1,
    name: 'Pendahuluan',
    courseId: courseId[8].id,
    totalDuration: 65,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 2,
    name: 'Memulai Product Management',
    courseId: courseId[8].id,
    totalDuration: 95,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 1,
    name: 'Pendahuluan',
    courseId: courseId[9].id,
    totalDuration: 65,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 2,
    name: 'Memulai iOS dengan Swift',
    courseId: courseId[9].id,
    totalDuration: 80,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 1,
    name: 'Pendahuluan',
    courseId: courseId[10].id,
    totalDuration: 65,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 2,
    name: 'Memulai Data Science',
    courseId: courseId[10].id,
    totalDuration: 105,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 1,
    name: 'Pendahuluan',
    courseId: courseId[11].id,
    totalDuration: 50,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 2,
    name: 'Memulai Android dengan Android Studio',
    courseId: courseId[11].id,
    totalDuration: 85,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]
