const { v4: uuidv4 } = require('uuid')

module.exports = (chapterId) => [
  // Course 1
  //// Chapter 1
  {
    name: 'HTML',
    id: uuidv4(),
    no: 1,
    chapterId: chapterId[0].id,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'CSS',
    id: uuidv4(),
    no: 2,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[0].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Javascript',
    id: uuidv4(),
    no: 3,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[0].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  //// Chapter 2
  {
    name: 'Apa itu React JS?',
    id: uuidv4(),
    no: 4,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[1].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Mengapa React JS Populer?',
    id: uuidv4(),
    no: 5,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[1].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Memulai dengan React JS',
    id: uuidv4(),
    no: 6,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[1].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  //// Chapter 3
  {
    name: 'Setup Proyek React JS',
    id: uuidv4(),
    no: 7,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[2].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Membuat Komponen Utama',
    id: uuidv4(),
    no: 8,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[2].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Menambahkan State dan Interaksi',
    id: uuidv4(),
    no: 9,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[2].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  //// Chapter 4
  {
    name: 'React Hooks',
    id: uuidv4(),
    no: 10,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[3].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Server-Side Rendering (SSR)',
    id: uuidv4(),
    no: 11,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[3].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Testing dalam React JS',
    id: uuidv4(),
    no: 12,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[3].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  //// Chapter 5
  {
    name: 'Animasi dengan React JS',
    id: uuidv4(),
    no: 13,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[4].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Form Handling dalam React JS',
    id: uuidv4(),
    no: 14,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[4].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Pengoptimalan Performa',
    id: uuidv4(),
    no: 15,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[4].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  //// Chapter 6
  {
    name: 'Membangun Proyek Akhir',
    id: uuidv4(),
    no: 16,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[5].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Course 2
  //// Chapter 1
  {
    name: 'Apa itu UI/UX Design?',
    id: uuidv4(),
    no: 1,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[6].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Peran Penting UI/UX Design',
    id: uuidv4(),
    no: 2,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[6].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Prinsip Desain UI/UX',
    id: uuidv4(),
    no: 3,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[6].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  //// Chapter 2
  {
    name: 'Pengenalan Alat Desain',
    id: uuidv4(),
    no: 4,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[7].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Menggunakan Adobe XD',
    id: uuidv4(),
    no: 5,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[7].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Menggunakan Figma',
    id: uuidv4(),
    no: 6,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[7].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  //// Chapter 3
  {
    name: 'Mengembangkan Proyek Desain',
    id: uuidv4(),
    no: 7,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[8].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Presentasi Desain',
    id: uuidv4(),
    no: 8,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[8].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Feedback dan Revisi',
    id: uuidv4(),
    no: 9,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[8].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  //// Chapter 4
  {
    name: 'Menjadi Profesional UI/UX',
    id: uuidv4(),
    no: 10,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[9].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Menyusun Portofolio',
    id: uuidv4(),
    no: 11,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[9].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 1',
    id: uuidv4(),
    no: 1,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[10].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 2',
    id: uuidv4(),
    no: 2,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[10].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 3',
    id: uuidv4(),
    no: 3,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[10].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 4',
    id: uuidv4(),
    no: 4,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[11].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 5',
    id: uuidv4(),
    no: 5,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[11].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 6',
    id: uuidv4(),
    no: 6,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[11].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 7',
    id: uuidv4(),
    no: 7,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[12].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 8',
    id: uuidv4(),
    no: 8,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[12].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 9',
    id: uuidv4(),
    no: 9,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[12].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 1',
    id: uuidv4(),
    no: 1,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[13].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 2',
    id: uuidv4(),
    no: 2,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[13].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 3',
    id: uuidv4(),
    no: 3,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[13].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 4',
    id: uuidv4(),
    no: 4,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[14].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 5',
    id: uuidv4(),
    no: 5,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[14].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 6',
    id: uuidv4(),
    no: 6,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[14].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 1',
    id: uuidv4(),
    no: 1,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[15].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 2',
    id: uuidv4(),
    no: 2,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[15].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 3',
    id: uuidv4(),
    no: 3,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[16].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 4',
    id: uuidv4(),
    no: 4,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[16].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 5',
    id: uuidv4(),
    no: 5,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[16].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 1',
    id: uuidv4(),
    no: 1,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[17].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 2',
    id: uuidv4(),
    no: 2,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[17].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 3',
    id: uuidv4(),
    no: 3,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[18].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 4',
    id: uuidv4(),
    no: 4,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[18].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 5',
    id: uuidv4(),
    no: 5,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[18].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 1',
    id: uuidv4(),
    no: 1,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[19].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 2',
    id: uuidv4(),
    no: 2,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[19].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 3',
    id: uuidv4(),
    no: 3,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[20].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 4',
    id: uuidv4(),
    no: 4,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[20].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 5',
    id: uuidv4(),
    no: 5,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[20].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 1',
    id: uuidv4(),
    no: 1,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[21].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 2',
    id: uuidv4(),
    no: 2,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[21].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 3',
    id: uuidv4(),
    no: 3,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[22].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 4',
    id: uuidv4(),
    no: 4,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[22].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 5',
    id: uuidv4(),
    no: 5,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[22].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 1',
    id: uuidv4(),
    no: 1,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[23].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 2',
    id: uuidv4(),
    no: 2,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[23].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 3',
    id: uuidv4(),
    no: 3,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[24].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 4',
    id: uuidv4(),
    no: 4,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[24].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 5',
    id: uuidv4(),
    no: 5,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[24].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 1',
    id: uuidv4(),
    no: 1,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[25].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 2',
    id: uuidv4(),
    no: 2,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[25].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 3',
    id: uuidv4(),
    no: 3,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[26].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 4',
    id: uuidv4(),
    no: 4,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[26].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 5',
    id: uuidv4(),
    no: 5,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[26].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 1',
    id: uuidv4(),
    no: 1,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[27].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 2',
    id: uuidv4(),
    no: 2,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[27].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 3',
    id: uuidv4(),
    no: 3,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[28].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 4',
    id: uuidv4(),
    no: 4,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[28].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 5',
    id: uuidv4(),
    no: 5,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[28].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 1',
    id: uuidv4(),
    no: 1,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[29].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 2',
    id: uuidv4(),
    no: 2,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[29].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 3',
    id: uuidv4(),
    no: 3,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[29].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 4',
    id: uuidv4(),
    no: 4,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[30].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 5',
    id: uuidv4(),
    no: 5,
    videoUrl:
      'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[30].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]
